# Generated by Django 5.2.8 on 2025-11-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carros/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
