# Generated by Django 5.2.8 on 2025-11-23 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0002_carro_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
